# Generated by Django 6.0.5 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_field_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="trello_api_key_encrypted",
            field=models.TextField(blank=True, help_text="Trello API key (encrypted)"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_board_id",
            field=models.CharField(blank=True, help_text="Target Trello board ID", max_length=100),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_enabled",
            field=models.BooleanField(default=False, help_text="Enable Trello task sync for run lifecycle states"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_last_sync_error",
            field=models.TextField(blank=True, default="", help_text="Last Trello sync error message"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_last_synced_at",
            field=models.DateTimeField(blank=True, help_text="When Trello sync last succeeded", null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_list_failed_id",
            field=models.CharField(blank=True, help_text="Trello list ID for failed/timeout/cancelled runs", max_length=100),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_list_queued_id",
            field=models.CharField(blank=True, help_text="Trello list ID for queued runs", max_length=100),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_list_running_id",
            field=models.CharField(blank=True, help_text="Trello list ID for running runs", max_length=100),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_list_success_id",
            field=models.CharField(blank=True, help_text="Trello list ID for successful runs", max_length=100),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="trello_token_encrypted",
            field=models.TextField(blank=True, help_text="Trello token (encrypted)"),
        ),
        migrations.AddField(
            model_name="run",
            name="trello_card_id",
            field=models.CharField(blank=True, db_index=True, help_text="Trello card ID for synced Kanban tracking", max_length=100),
        ),
    ]
